Need to install: `conda install -c anaconda scikit-learn`

In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.model_selection import ShuffleSplit
initDS = np.arange(20)
splitter = ShuffleSplit(n_splits=4, test_size=0.2, random_state=0)
for trainDS, testDS in splitter.split(initDS) :
    print(trainDS, testDS)

[10 17  6 13  4  2  5 14  9  7 16 11  3  0 15 12] [18  1 19  8]
[ 2 12 19 16 10  0  3  4 15  8 13  9  5 14  7  6] [11  1 18 17]
[11  2  8  6  3 17  4 10 16 18  9  1  0  7 14 19] [15 13 12  5]
[ 3 17  7 12 14 16 11 10  9 15  1 19  8  6  5  4] [18  0 13  2]


In [4]:
initDS = np.arange(100).reshape(5,20)
splitter = ShuffleSplit(n_splits=4, test_size=0.4, random_state=0)
for trainDS, testDS in splitter.split(initDS) :
    print(trainDS, testDS)

[1 3 4] [2 0]
[1 4 3] [0 2]
[4 0 2] [1 3]
[2 4 0] [3 1]


In [5]:
initDS

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [8]:
input_file = 'http://bit.ly/36w1jgf'
all = pd.read_csv(input_file, header=None, sep=',')
all.head(2), all.tail(2)

(     0     1     2    3     4     5     6     7    8     9   ...   48     49  \
 0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.0  0.00  ...  0.0  0.000   
 1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.0  0.94  ...  0.0  0.132   
 
     50     51    52     53     54   55    56  57  
 0  0.0  0.778  0.00  0.000  3.756   61   278   1  
 1  0.0  0.372  0.18  0.048  5.114  101  1028   1  
 
 [2 rows x 58 columns],
       0    1     2    3     4    5    6    7    8    9   ...   48     49   50  \
 18  0.96  0.0  0.00  0.0  0.32  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.057  0.0   
 19  0.00  0.0  0.65  0.0  0.00  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.000  0.0   
 
        51   52   53     54  55  56  57  
 18  0.000  0.0  0.0  1.147   5  78   0  
 19  0.125  0.0  0.0  1.250   5  40   0  
 
 [2 rows x 58 columns])

In [9]:
labels = [int(i) for i in (10 * '1' + 10 * '0')]
len(labels)

20

In [11]:
from sklearn.model_selection import train_test_split
data_train, data_test, label_train, label_test = train_test_split(all, labels, test_size=0.4, random_state=0)

data_train, data_test, label_train, label_test

(      0     1     2    3     4     5     6     7     8     9   ...    48  \
 4   0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
 2   0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
 5   0.00  0.00  0.00  0.0  1.85  0.00  0.00  1.85  0.00  0.00  ...  0.00   
 14  0.00  0.00  1.19  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
 9   0.06  0.12  0.77  0.0  0.19  0.32  0.38  0.00  0.06  0.00  ...  0.04   
 7   0.00  0.00  0.00  0.0  1.88  0.00  0.00  1.88  0.00  0.00  ...  0.00   
 16  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
 11  0.00  0.00  1.25  0.0  2.50  0.00  0.00  0.00  0.00  0.00  ...  0.00   
 3   0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
 0   0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
 15  0.31  0.00  0.62  0.0  0.00  0.31  0.00  0.00  0.00  0.00  ...  0.00   
 12  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   